--Procedimiento Gestion_Inversion (datos de la inversión “actual”).
create or replace 
PROCEDURE GESTION_INVERSION (DNINEW INVIERTE.DNI%TYPE, NOMBREEMPRESA EMPRESA.NOMBREE%TYPE, CANTIDADNEW INVIERTE.CANTIDAD%TYPE, TIPONEW INVIERTE.TIPO%TYPE) AS
plsql_block VARCHAR(500);
plsql_block2 VARCHAR(500);
sec NUMBER;
BEGIN
CREA_SEC_INVERSION(NOMBREEMPRESA);
CREA_TABLA_INVERSIONES(NOMBREEMPRESA);
plsql_block2:='SELECT SEC_' || NOMBREEMPRESA || ' INTO sec FROM DUAL;';
EXECUTE IMMEDIATE plsql_block2;
plsql_block := 'INSERT INTO INVERSIONES_' || NOMBREEMPRESA || 'VALUES (:a, :b, :c, :d);';
EXECUTE IMMEDIATE plsql_block USING IN DNINEW, CANTIDADNEW, TIPONEW, sec;
dbms_output.put_line('Insertado en la tabla invierte_' || NOMBREEMPRESA || ' valores: ' || DNINEW || ' ' || TIPONEW || ' ' || CANTIDADNEW);
END;

--Procedimiento crea_sec_inversion
create or replace 
procedure CREA_SEC_INVERSION (NOMBREEMPRESA IN EMPRESA.NOMBREE%TYPE) AS
existe NUMBER;
plsql_block VARCHAR(500);
BEGIN
SELECT COUNT(*) INTO existe FROM USER_OBJECTS WHERE OBJECT_NAME='SEC_' || NOMBREEMPRESA;

IF existe = 0 THEN
  plsql_block:='CREATE SEQUENCE SEC_' || NOMBREEMPRESA;
  EXECUTE IMMEDIATE plsql_block;
END IF;

END;

--Procedimiento crea_tabla_inversiones

create or replace 
PROCEDURE CREA_TABLA_INVERSIONES (NOMBREEMPRESA IN EMPRESA.NOMBREE%TYPE) AS
existe NUMBER;
plsql_block VARCHAR(500);
BEGIN
SELECT COUNT(*) INTO existe FROM TABS WHERE TABLE_NAME='INVERSIONES_' || NOMBREEMPRESA;
IF existe = 0 THEN
  plsql_block:='CREATE TABLE INVERSIONES_' || NOMBREEMPRESA || ' (DNI VARCHAR(8), CANTIDAD FLOAT, TIPO VARCHAR(20), NUMSEC NUMBER, PRIMARY KEY(NUMSEC))';
  EXECUTE IMMEDIATE plsql_block;
END IF;

END;